### ISSUE TITLE
It doesnt update table

### ISSUE THREAD

**Issue by Pdzly** [ceifa/sqlier#17]
I have a question / issue:

If i update the model, i need to change the table idk why but without it it says
"[SQLITE] Error in query: INSERT INTO `usr`(`SteamId64`, `Type`, `ServerID`, `time`, `date`) VALUES('76561198141223467', 'true', '1', 'ime', '06/24/21') ~ Error: table usr has no column named time "

**Comment by ceifa** [comment]
Yes, sqlier create but doesn't update your tables, if you change the model you will have to do it by yourself. If you are still developing something, just drop your table and sqlier will create it again.
