### ISSUE TITLE
Whats that? an Error ;)

### ISSUE THREAD

**Issue by Pdzly** [ceifa/sqlier#20]
![image](https://user-images.githubusercontent.com/34943569/126069691-a8bf22e2-9b24-4ee5-862d-9557747ec28a.png)

**Comment by Pdzly** [comment]
I tried to delete an model

**Comment by Pdzly** [comment]
Groupmodel = sqlier.Model({
        Table = "groups",
        Columns = {
            Id = {
                Type = sqlier.Type.Integer
            },
            Name = {
                Type = sqlier.Type.String
            }
        },
        Database = "mk_db"
    })

**Comment by ceifa** [comment]
I guess the error is not related to this piece of code. It seems like an error when deleting. Are you calling delete somewhere in your code?

**Comment by Pdzly** [comment]
yup like

local myinst = Groupmodel({
   Id = 0,
   Name = "Baum"
})
myinst:save()
myinst:delete()

**Comment by Pdzly** [comment]
i havent got the 100% "original" code of mine but it should work like in the example said.

**Comment by ceifa** [comment]
Fixed on last commit!
