### ISSUE TITLE
Thats not an edge case

### ISSUE THREAD

**Issue by Pdzly** [ceifa/sqlier#21]
It makes an error if the table with the filter is empty
![image](https://user-images.githubusercontent.com/34943569/126077560-98d6efaf-5307-46b0-83cf-228079a79567.png)

Unusable with that!

**Comment by Pdzly** [comment]
Groupmodel = sqlier.Model({
        Table = "groups",
        Columns = {
            Id = {
                Type = sqlier.Type.Integer
            },
            Name = {
                Type = sqlier.Type.String
            }
        },
        Database = "mk_db"
    })

    local filt = {
        Id = "0",
    }
    Groupmodel:filter(filt, function(gps)
        if (gps == nil) then
            local default = Groupmodel({
                Id = 0,
                Name = "Nicht Zugewiesen"
            })

            default:save()
        end
    end)

**Comment by ceifa** [comment]
Fixed on last commit!

**Comment by ceifa** [comment]
I suggest you to add the `Id` as an identity on the model and instead of using `filter`, use `get`, because it's faster. If you will still using filter, fyi it will never send `nil` on your callback, you can check if it's empty with `#gps == 0`
