### ISSUE TITLE
:save() creating duplicates

### ISSUE THREAD

**Issue by GlorifiedPig** [ceifa/sqlier#24]
Hey, I instantiate a model for use later in the code. I call the first :save() and it inserts fine into the database. However, when I update certain information later and call :save() again it inserts a new entry, with all the same data except the incremented ID. This seems to only happen when I use the auto increment ID as my primary key. When I call :save() and the primary key is, for instance, a SteamID, it seems to work fine.

**Comment by ceifa** [comment]
That is weird, can you show how are you defining your model?
Also, can you make a `PrintTable` of the instance before the save?

**Comment by GlorifiedPig** [comment]
How I'm defining the model:

```lua
local model = {
    Reports = sqlier.Model( {
        Table = "reports",
        Database = databaseName,
        Columns = {
            ID = {
                Type = sqlier.Type.Integer,
                AutoIncrement = true
            },
            Time = {
                Type = sqlier.Type.Integer
            },
            Staff = {
                Type = sqlier.Type.SteamId64
            },
            Reporter = {
                Type = sqlier.Type.SteamId64
            }
        },
        Identity = "ID"
    } )
}
```

PrintTable before saving:

```
Reporter        =       76561198073308340
Staff   =       76561198073308340
Time    =       1652311572
model   =       function: 0x2b2f0908
```

I then call :save() twice on the same model, and it creates two instances.

**Comment by GlorifiedPig** [comment]
Also, running `:delete()` on the same instantiated model also does nothing in this case.

**Comment by ceifa** [comment]
Fixed in https://github.com/ceifa/sqlier/commit/6504883d51b3d8a5dad671a2be544cbdb3d9e79a

**Comment by ceifa** [comment]
If you are using mysql, you should either use the `queue` option or wait for the operation using the callback parameter:

> Option 1:

`sqlier.Initialize("db2", "mysqloo", { queue = true })`

> Option 2:

`
report:save(function()
    -- here we know that the save operation is done
    report:delete()
end)
`

In other drivers it should work well without any tricks.

**Comment by GlorifiedPig** [comment]
Oh yeah right, don't know how I didn't pick that up, thanks for fixing :)
